import type { EarthquakeFeature, EonetEvent } from '@terrawatch/shared';

export const mockEarthquakes: EarthquakeFeature[] = [
  {
    type: 'Feature',
    id: 'us7000abc1',
    properties: {
      mag: 5.2,
      place: '10km NE of Tokyo, Japan',
      time: 1706745600000,
      updated: 1706745600000,
      url: 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000abc1',
      detail: '',
      felt: 120,
      cdi: null,
      mmi: null,
      alert: null,
      status: 'reviewed',
      tsunami: 0,
      sig: 416,
      net: 'us',
      code: '7000abc1',
      ids: ',us7000abc1,',
      sources: ',us,',
      types: ',origin,',
      nst: null,
      dmin: null,
      rms: 0.5,
      gap: null,
      magType: 'mww',
      type: 'earthquake',
      title: 'M 5.2 - 10km NE of Tokyo, Japan',
    },
    geometry: { type: 'Point', coordinates: [139.75, 35.68, 30] },
  },
  {
    type: 'Feature',
    id: 'us7000abc2',
    properties: {
      mag: 3.1,
      place: '15km SW of Los Angeles, CA',
      time: 1706832000000,
      updated: 1706832000000,
      url: 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000abc2',
      detail: '',
      felt: 10,
      cdi: null,
      mmi: null,
      alert: null,
      status: 'reviewed',
      tsunami: 0,
      sig: 150,
      net: 'us',
      code: '7000abc2',
      ids: ',us7000abc2,',
      sources: ',us,',
      types: ',origin,',
      nst: null,
      dmin: null,
      rms: 0.3,
      gap: null,
      magType: 'ml',
      type: 'earthquake',
      title: 'M 3.1 - 15km SW of Los Angeles, CA',
    },
    geometry: { type: 'Point', coordinates: [-118.24, 34.05, 8] },
  },
];

export const mockHighMagEarthquake: EarthquakeFeature = {
  type: 'Feature',
  id: 'us7000abc3',
  properties: {
    mag: 8.9,
    place: 'Near the coast of Chile',
    time: 1706918400000,
    updated: 1706918400000,
    url: 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000abc3',
    detail: '',
    felt: 5000,
    cdi: null,
    mmi: null,
    alert: 'red',
    status: 'reviewed',
    tsunami: 1,
    sig: 900,
    net: 'us',
    code: '7000abc3',
    ids: ',us7000abc3,',
    sources: ',us,',
    types: ',origin,',
    nst: null,
    dmin: null,
    rms: 1.2,
    gap: null,
    magType: 'mww',
    type: 'earthquake',
    title: 'M 8.9 - Near the coast of Chile',
  },
  geometry: { type: 'Point', coordinates: [-71.63, -33.04, 25] },
};

export const mockEonetEvents: EonetEvent[] = [
  {
    id: 'EONET_001',
    title: 'Wildfire - Northern California',
    description: null,
    link: 'https://eonet.gsfc.nasa.gov/api/v3/events/EONET_001',
    closed: null,
    categories: [{ id: 'wildfires', title: 'Wildfires' }],
    sources: [{ id: 'InciWeb', url: 'https://inciweb.wildfire.gov' }],
    geometry: [
      {
        magnitudeValue: null,
        magnitudeUnit: null,
        date: '2025-01-15T00:00:00Z',
        type: 'Point',
        coordinates: [-122.42, 37.77],
      },
    ],
  },
  {
    id: 'EONET_002',
    title: 'Severe Storm - Gulf of Mexico',
    description: null,
    link: 'https://eonet.gsfc.nasa.gov/api/v3/events/EONET_002',
    closed: '2025-01-20T00:00:00Z',
    categories: [{ id: 'severeStorms', title: 'Severe Storms' }],
    sources: [{ id: 'NOAA_NHC', url: 'https://www.nhc.noaa.gov' }],
    geometry: [
      {
        magnitudeValue: null,
        magnitudeUnit: null,
        date: '2025-01-10T00:00:00Z',
        type: 'Point',
        coordinates: [-90.07, 29.95],
      },
    ],
  },
];
